
# Turned into a GitHub Actions composite action, original YML from:
#   https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

name: Deploy to nomad cluster
description: 'Deploys a github built docker image from its registry to a nomad cluster'
author: internetarchive
branding:
  icon: 'globe'
  color: 'white'

runs:
  # https://gitlab.com/internetarchive/nomad
  image: 'docker://registry.gitlab.com/internetarchive/nomad/master'
  using: 'docker'
  env:
    BASE_DOMAIN: ${{ inputs.BASE_DOMAIN }}
    NOMAD_ADDR: ${{ inputs.NOMAD_ADDR }}
    NOMAD_TOKEN: ${{ inputs.NOMAD_TOKEN }}
    NOMAD_TOKEN_PROD: ${{ inputs.NOMAD_TOKEN_PROD }}
    REGISTRY_TOKEN: ${{ inputs.REGISTRY_TOKEN }}
    NOMAD_SECRETS: ${{ inputs.NOMAD_SECRETS }}
    PRIVATE_REPO: ${{ inputs.PRIVATE_REPO }}
    NOMAD_VAR_CHECK_PATH: ${{ inputs.NOMAD_VAR_CHECK_PATH }}
    NOMAD_VAR_CHECK_PROTOCOL: ${{ inputs.NOMAD_VAR_CHECK_PROTOCOL }}
    NOMAD_VAR_CHECK_TIMEOUT: ${{ inputs.NOMAD_VAR_CHECK_TIMEOUT }}
    NOMAD_VAR_COUNT: ${{ inputs.NOMAD_VAR_COUNT }}
    NOMAD_VAR_CPU: ${{ inputs.NOMAD_VAR_CPU }}
    NOMAD_VAR_HEALTH_TIMEOUT: ${{ inputs.NOMAD_VAR_HEALTH_TIMEOUT }}
    NOMAD_VAR_HOME: ${{ inputs.NOMAD_VAR_HOME }}
    NOMAD_VAR_HOSTNAMES: ${{ inputs.NOMAD_VAR_HOSTNAMES }}
    NOMAD_VAR_MEMORY: ${{ inputs.NOMAD_VAR_MEMORY }}
    NOMAD_VAR_MULTI_CONTAINER: ${{ inputs.NOMAD_VAR_MULTI_CONTAINER }}
    NOMAD_VAR_NETWORK_MODE: ${{ inputs.NOMAD_VAR_NETWORK_MODE }}
    NOMAD_VAR_NO_DEPLOY: ${{ inputs.NOMAD_VAR_NO_DEPLOY }}
    NOMAD_VAR_PERSISTENT_VOLUME: ${{ inputs.NOMAD_VAR_PERSISTENT_VOLUME }}
    NOMAD_VAR_PORTS: ${{ inputs.NOMAD_VAR_PORTS }}
  args:
    # https://gitlab.com/internetarchive/nomad/-/blob/master/deploy.sh
    - /deploy.sh

inputs:
  BASE_DOMAIN:
    description: 'nomad cluster wildcard DNS domain name, eg: example.com'
    required: true

  NOMAD_ADDR:
    description: 'nomad cluster API endpoint - archive.org deploys automate this but you can override'
    required: false

  NOMAD_TOKEN:
    description: 'nomad cluster credentials - store in your repo GitHub Secrets'
    required: true

  NOMAD_TOKEN_PROD:
    description: 'nomad archive.org production cluster credentials - store in your repo GitHub Secrets'
    default: ''
    required: false

  REGISTRY_TOKEN:
    description: 'for registry'
    required: true

  PRIVATE_REPO:
    description: 'automatically set for smoother redeploys'
    require: true
    default: ${{ github.event.repository.private }}

  NOMAD_SECRETS:
    # NOTE: requires '=' char key/val separator instead of ':' (which would be actual JSON).
    # NOTE: the values *in reality* should all be like the last value.
    # Example: {"A"="xxx", "STRINGY"="i'm \"json-like\"", "MY_TOKEN"="${{ secrets.MY_TOKEN }}"}
    description: 'json-like key/value string which become env vars in your running deployment shell'
    required: false


  NOMAD_VAR_CHECK_PATH:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_CHECK_PROTOCOL:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_CHECK_TIMEOUT:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_COUNT:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_CPU:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_HEALTH_TIMEOUT:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_HOME:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_HOSTNAMES:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_MEMORY:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_MULTI_CONTAINER:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_NETWORK_MODE:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_NO_DEPLOY:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_PERSISTENT_VOLUME:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false

  NOMAD_VAR_PORTS:
    description: '@see https://gitlab.com/internetarchive/nomad#customizing'
    required: false
